### ISSUE TITLE
咨询帖

### ISSUE THREAD

**Issue by qp91abc1234** [MrQinYQ/vite-plugin-dynamic-chunk#1]
看了你的代码，非常感谢~
请教一波，css 为啥没进行分包处理
感谢

**Comment by MrQinYQ** [comment]
最近我使用的技术栈比较偏向css-in-js, 比如：antd。这样css的分包实际上就是js的分包。
如果你使用的是无样式组件库，比如Headless UI。我理解是否也不依赖工程化对css的分包？

**Comment by MrQinYQ** [comment]
如果你认为有必要对css进行分包的话，也可以提个pr

**Comment by qp91abc1234** [comment]
话说现在 http2 多路复用并行加载的情况下，还有必要合并主入口引用的 npm 包到 vendor chunk 中么，你怎么看待这个问题呢？

**Comment by MrQinYQ** [comment]
根据历史经验来看unpak方案是会对fmp指标存在一定程度的劣化，因为http2仍然存在请求头阻塞问题，如果用户的网络并不稳定，我们请求的文件过多，对指标的负向影响比较严重。所以我所接触的项目几乎没有使用这种方案。
